import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/db/supabase-server";
import { getSessionById } from "@/lib/db/queries";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const supabase = await createSupabaseServer();
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      return new NextResponse("Unauthorized", { status: 401 });
    }

    const session = await getSessionById(user.id, id);
    if (!session) {
      return new NextResponse("Session not found", { status: 404 });
    }

    // Generate a simple text-based PDF content
    const pdfContent = generatePDFContent(session);
    
    return new NextResponse(pdfContent, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="triage-${id.slice(0, 8)}.txt"`,
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return new NextResponse("Internal Server Error", { status: 500 });
  }
}

function generatePDFContent(session: any): string {
  const date = new Date(session.created_at).toLocaleDateString();
  const time = new Date(session.created_at).toLocaleTimeString();
  
  let content = `MEDITRIAGE - SYMPTOM CHECK REPORT\n`;
  content += `=====================================\n\n`;
  content += `Date: ${date} at ${time}\n`;
  content += `Patient: ${session.patient_name || "Self"}\n`;
  content += `Language: ${session.language}\n`;
  content += `Status: ${session.status}\n\n`;
  
  if (session.final_severity) {
    content += `ASSESSMENT RESULT\n`;
    content += `-----------------\n`;
    content += `Severity: ${session.final_severity.replace('_', ' ').toUpperCase()}\n\n`;
  }
  
  if (session.doctor_summary) {
    content += `DOCTOR SUMMARY\n`;
    content += `--------------\n`;
    content += `${session.doctor_summary}\n\n`;
  }
  
  if (session.red_flags && Array.isArray(session.red_flags) && session.red_flags.length > 0) {
    content += `RED FLAGS\n`;
    content += `---------\n`;
    session.red_flags.forEach((flag: string, index: number) => {
      content += `${index + 1}. ${flag}\n`;
    });
    content += `\n`;
  }
  
  if (session.conversation && Array.isArray(session.conversation)) {
    content += `CONVERSATION TRANSCRIPT\n`;
    content += `=======================\n\n`;
    
    session.conversation.forEach((message: any, index: number) => {
      const role = message.role === 'user' ? 'YOU' : 'AI ASSISTANT';
      const timestamp = message.ts ? new Date(message.ts).toLocaleTimeString() : '';
      content += `[${timestamp}] ${role}:\n`;
      content += `${message.content}\n\n`;
    });
  }
  
  content += `\n\nDISCLAIMER\n`;
  content += `==========\n`;
  content += `This report is generated by an AI system and is for informational purposes only. `;
  content += `It is not a substitute for professional medical advice, diagnosis, or treatment. `;
  content += `Always seek the advice of your physician or other qualified health provider with any `;
  content += `questions you may have regarding a medical condition.\n\n`;
  content += `Generated by MediTriage AI - ${new Date().toISOString()}\n`;
  
  return content;
}